runtime: nodejs10

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
  redirect_http_response_code: 301

- url: /
  static_dir: static
  secure: always
  redirect_http_response_code: 301
