runtime: go113

handlers:

- url: /
  static_files: src/index.html
  upload: src/index.html
  secure: always
  redirect_http_response_code: 301

- url: /submit
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /
  static_dir: src
  secure: always
  redirect_http_response_code: 301
